name: Flutter CI/CD

on:
  push:
    branches: [dev, staging, main]
  pull_request:
    branches: [dev, staging, main]

jobs:
  build-test:
    name: Build & Test Flutter App
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android, web]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Cache Flutter SDK and Pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ env.FLUTTER_ROOT }}/bin/cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run unit tests
        run: flutter test

      - name: Build Flutter app for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" = "android" ]; then
            flutter build apk --release
          elif [ "${{ matrix.platform }}" = "web" ]; then
            flutter build web
          else
            echo "Unsupported platform ${{ matrix.platform }}"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk
            build/web/

  deploy:
    name: Deploy to Firebase
    needs: build-test
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'

    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      FIREBASE_APP_ID_ANDROID: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
      FIREBASE_APP_ID_WEB: ${{ secrets.FIREBASE_APP_ID_WEB }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Install dependencies
        run: flutter pub get

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Android APK
        if: github.ref != 'refs/heads/dev'
        run: flutter build apk --release

      - name: Build Web App
        run: flutter build web

      - name: Deploy Android APK to Firebase App Distribution
        if: github.ref != 'refs/heads/dev'
        run: |
          firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app $FIREBASE_APP_ID_ANDROID \
            --token $FIREBASE_TOKEN \
            --groups "testers"

      - name: Deploy Web App to Firebase Hosting
        run: |
          firebase deploy --only hosting \
            --token $FIREBASE_TOKEN
